CREATE TABLE users(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(128) NOT NULL
);

CREATE TABLE notes(
  id VARCHAR(36) PRIMARY KEY,
  workspace VARCHAR(36) NOT NULL,
  title VARCHAR(2000) NOT NULL
);
