H = HillCryptosystem(AlphabeticStrings(), 3)
K = H.random_key()
M = H.encoding("WARNINGIFYOUCANREADTHISYOUSTILLHAVEACHANCETOLIVEWALKFASTERANDDONTLOOKBACKIREPEATDONOTLOOKBACK")
cipher = H.enciphering(K, M)
print("Ciphertet:", cipher)
print("Plaintet:", H.deciphering(K, cipher))
print("Key:", K)
print(H.deciphering(K, H.enciphering(K, M)) == M)
#Ciphertet: RRVXGQYTDXYKPDTLHNPJTZAKREIWNHFWUSOLZYCNYBXJNMPTKFLPALGGPAQTGRONBLCLKGUDYTHFUJMMAINZVHIWNXGO
#Plaintet: WARNINGIFYOUCANREADTHISYOUSTILLHAVEACHANCETOLIVEWALKFASTERANDDONTLOOKBACKIREPEATDONTLOOKBACK
# Flag = CBC{WARNINGIFYOUCANREADTHISYOUSTILLHAVEACHANCETOLIVEWALKFASTERANDDONTLOOKBACKIREPEATDONTLOOKBACK}
#Key: [23  3  0  6]
#[10 10  4 15]
#[24 17 15 15]
#[15 22  8 16]